from utilidades.le_chave import le_chave
from utilidades.tem_registro import tem_registro
from utilidades.byte_offset_pelo_id import byte_offset
from utilidades.registro import le_registro
from utilidades.byte_offset_decimal import byte_offset_d