from utilidades.le_chave import le_chave
from utilidades.tem_registro import tem_registro
from utilidades.byte_offset_pelo_id import byte_offset
from utilidades.registro import le_registro
from utilidades.led import Membro_led
from utilidades.led import b_o_prox_led
from utilidades.led import tam_regis_da_led
from utilidades.led import remove_da_led
from utilidades.testa_dat import testa_dat